AdminPanel/AdminPanel/Controllers/UploadController.cs
using AdminPanel.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using static AdminPanel.Models.UploadModel;

namespace AdminPanel.Controllers
{
    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult Index()
        {
            return View();
        }

        #region[Bank Details]
        public ActionResult BankDetails()
        {
            List<BankDetails> list = new List<BankDetails>();
            list = UploadServices.GetBankDetails();
            return View(list);
        }
        public JsonResult DeleteBankDetails(string id)
        {
            bool IsSuccess = UploadServices.DeleteBankDetails(id);
            return Json(IsSuccess);
        }
        public JsonResult AddBankDetails(BankDetails model)
        {
            bool IsSuccess = UploadServices.AddBankDetails(model);
            return Json(IsSuccess);
        }
        #endregion

        #region[Agency Credit And Debit]
        public ActionResult AgencyCreditAndDebit()
        {
            if (Session["AgentList"] == null)
            {
                Session["AgentList"] = UploadServices.AgencyStokistList_ddl();
            }
            ViewBag.AgentList = Session["AgentList"];
            return View();
        }
        #endregion

        #region[Agency Credit Limit]
        public ActionResult SetAgencyCreditLimit(string userId=null)
        {
            if (Session["AgentList"] == null)
            {
              //Session["AgentList"] = UploadServices.AgencyList_ddl();
                Session["AgentList"] = UploadServices.AgencyStokistList_ddl();
            }
            ViewBag.AgencyList = Session["AgentList"];

            ViewBag.AgencyDetail_display = "none";
            ViewBag.AgencyCredit_display = "none";

            Models.ProfileModel.Agency model = new Models.ProfileModel.Agency();

            if (!string.IsNullOrEmpty(userId))
            {
                model = UploadServices.GetAgencyDetails(userId);
                if (model.Counter > 0) {
                    ViewBag.AgencyDetail_display = "block";
                    ViewBag.AgencyCredit_display = "block";
                }
            }
            return View(model);
        }

        [HttpPost]
        public ActionResult SetAgencyCreditLimit(string Id,string creditlimit, string expirydate, string remarks)
        {
            Models.ExecuRegister lu = ((List<Models.ExecuRegister>)HttpContext.Session["executive"])[0];
            string userid = lu.user_id;

            bool IsSuccess = UploadServices.UpdateAgencyCreditLimit(Id, creditlimit, expirydate, remarks);
            return RedirectToAction("SetAgencyCreditLimit");
        }
        #endregion
    }
}

AdminPanel/AdminPanel/Views/Upload/AgencyCreditAndDebit.cshtml
@*@model IEnumerable<AdminPanel.Models.FlightSettingModel.FareTypeMaster>*@
@{
    ViewBag.Title = "AgencyCreditAndDebit";
    Layout = "~/Views/Shared/_MasterLayoutPage.cshtml";
}

<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <h2>Agency Credit and Debit</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br>
                @using (Html.BeginForm())
                {
                    <div class="item form-group col-md-3 col-sm-3">
                        <div class="col-md-12 col-sm-12 ">
                            <select name="agencyId" required class="form-control">
                                @*<option value="volvo">Volvo</option>*@
                                @Html.Raw(ViewBag.AgentList)
                            </select>
                        </div>
                    </div>

                    <div class="item form-group col-md-3 col-sm-3 ">
                        <div class="col-md-12 col-sm-12">
                            <button type="submit" class="btn btn-success pull-left" style="width:120px;">Submit</button>
                            <button type="reset" class="btn btn-primary pull-right" style="width:120px;">Reset</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel" style="padding: 0px!important;">
            <div class="x_content">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive text-nowrap tablescroll">
                            <table class="table" data-toggle="table" id="IncentiveTable">
                                <thead>
                                    <tr style="background:#f6f6f6;">
                                        <th>Sr.No</th>
                                        <th>Debit Note</th>
                                        <th>Credit Note</th>
                                        <th>Agency Name</th>
                                        <th>User_Id</th>
                                        <th>AgencyId</th>
                                        <th>Balance</th>
                                        <th>Due_Amount</th>
                                        <th>CreditLimit</th>
                                        <th>Mobile</th>
                                        <th>Email</th>
                                        <th>Sales Agent</th>
                                        <th>Transaction Date</th>
                                    </tr>
                                </thead>
                                <tbody id="tbodycomm">
                                    @*@if (Model.Count() > 0)
                                        {
                                            foreach (var item in Model)
                                            {
                                                <tr>
                                                    <td>@item.FareType</td>
                                                    <td>@item.DisplayName</td>
                                                    <td>@item.Remark</td>
                                                    <td>@item.UpdatedDate</td>
                                                    <td>@item.UpdatedBy</td>
                                                </tr>
                                            }
                                        }
                                        else
                                        {
                                            <tr style="text-align:center">
                                                <td colspan="5" style="color:red;">No Record Found</td>
                                            </tr>
                                        }*@
                                    <tr style="text-align:center">
                                        <td colspan="5" style="color:red;">No Record Found</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

AdminPanel/AdminPanel/Views/Upload/BankDetails.cshtml
@model IEnumerable<AdminPanel.Models.UploadModel.BankDetails>
@{
    ViewBag.Title = "BankDetails";
    Layout = "~/Views/Shared/_MasterLayoutPage.cshtml";
}
@section header{
    <link href="~/Content/design/dropdown_search_box/css/select2.min.css" rel="stylesheet" />
}

<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <h2><i class="fa fa-bank"></i>&nbsp;Bank Detail</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <div class="row">
                    <div class="col-md-3 col-sm-12  form-group">
                        <input id="bankname" type="text" placeholder="Bank Name" class="form-control commoncss" />
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        <input id="branchname" type="text" placeholder="Branch Name" class="form-control commoncss" />
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        <input id="area" type="text" placeholder="Area Name" class="form-control commoncss" />
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        <input id="accNumber" type="text" placeholder="Account Number" class="form-control commoncss" />
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-3 col-sm-12  form-group">
                        <input id="ifsc" type="text" placeholder="IFSC Code" class="form-control commoncss" />
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        <select class="form-control commoncss" id="distributer">
                            <option value="0">Select Distributer</option>
                            <option value="HEADOFFICE">HEADOFFICE</option>
                        </select>
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        <button type="submit" id="submit" class="btn btn-success btn-xs form-control">Submit</button>
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        <button type="submit" id="reset" class="btn btn-success btn-xs form-control">Reset</button>
                    </div>
                </div>
            </div>
        </div>

        <div class="x_panel" style="padding: 0px!important;">
            <div class="x_content">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive text-nowrap">
                            <table class="table" data-toggle="table" id="IncentiveTable">
                                <thead>
                                    <tr style="background:#f6f6f6;">
                                        <th>Bank Name</th>
                                        <th>Branch Name</th>
                                        <th>Area</th>
                                        <th>Account No</th>
                                        <th>IFSC Code</th>
                                        <th>Distrid</th>
                                        <th>Action</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @if (Model.Count() > 0)
                                    {
                                        foreach (var item in Model)
                                        {
                                            <tr id=@item.id>
                                                <td>@item.BankName</td>
                                                <td>@item.BranchName</td>
                                                <td>@item.Area</td>
                                                <td>@item.AccountNumber</td>
                                                <td>@item.NEFTCode</td>
                                                <td>@item.DISTRID</td>
                                                <td style="cursor:pointer;" id="delete_@item.id"><span class="badge badge-danger" onclick="DeleteBankDetails(@item.id)"><i class="fa fa-times-circle"></i>Delete</span></td>
                                            </tr>
                                        }
                                    }
                                    else
                                    {
                                        <tr style="text-align:center">
                                            <td colspan="6" style="color:red;">No Record Found</td>
                                        </tr>
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section footer
{
    <script src="~/Content/js/custom/common.js"></script>
    <script src="~/Content/design/dropdown_search_box/js/select2.min.js"></script>
    <script>
        //dropdown with search box
        $("#distributer").select2();

        $(function () {
            let datacount = 0;
        datacount = @Model.Count();
            });
    </script>
    <script src="~/Content/js/Upload/BankDetails.js"></script>
}

AdminPanel/AdminPanel/Views/Upload/SetAgencyCreditLimit.cshtml
@model AdminPanel.Models.ProfileModel.Agency
@{
    ViewBag.Title = "SetAgencyCreditLimit";
    Layout = "~/Views/Shared/_MasterLayoutPage.cshtml";
}
@section header{
    <link href="~/Content/design/dropdown_search_box/css/select2.min.css" rel="stylesheet" />
}
<div class="row">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_title">
                <h2>Set Agency Credit Limit</h2>
                <div class="clearfix"></div>
            </div>
            <div class="x_content">
                <br>
                @using (Html.BeginForm("SetAgencyCreditLimit","Upload", FormMethod.Get))
                {
                    <div class="item form-group">
                        <div class="col-md-6 col-sm-6 ">
                            <select name="userId" id="ddlAgencyList" required class="form-control ">
                                @Html.Raw(ViewBag.AgencyList)
                            </select>
                        </div>
                        <div class="col-md-3 col-sm-3">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

<div class="row" style="display:@ViewBag.AgencyDetail_display;">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel" style="padding: 0px!important;">
            <div class="x_content">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="table-responsive text-nowrap tablescroll" style="height: 150px;">
                            <table class="table" data-toggle="table" id="IncentiveTable">

                                <tbody id="tbodycomm">
                                    <tr>
                                        <td>Total Balance</td>
                                        <td>xxxxxx</td>
                                        <td>User Id/Agency Id</td>
                                        <td>@Model.User_Id/@Model.AgencyId</td>
                                        <td>Mobile</td>
                                        <td>@Model.Mobile</td>

                                    </tr>
                                    <tr>
                                        <td>Agent Credit Limit</td>
                                        <td>@Model.Crd_Limit</td>
                                        <td>Name</td>
                                        <td>@Model.Title @Model.Fname @Model.Mname @Model.Lname</td>
                                        <td>Email</td>
                                        <td>@Model.Email</td>
                                    </tr>
                                    <tr>
                                        <td>Due Amount</td>
                                        <td>@Model.DueAmount</td>
                                        <td>Agency Name</td>
                                        <td>@Model.Agency_Name</td>
                                        <td>Address</td>
                                        <td>@Model.Address</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="row" style="display:@ViewBag.AgencyCredit_display;">
    <div class="col-md-12 col-sm-12 ">
        <div class="x_panel">
            <div class="x_content">
                <br>
                @using (Html.BeginForm("SetAgencyCreditLimit", "Upload", FormMethod.Post))
                {
                    <div class="item form-group">
                        <div class="col-sm-4 col-md-4">
                            <label class="col-form-label col-md-4 col-sm-4 ">
                                Agency Details:
                            </label>
                            <input type="text" style="display:none" name="id" value="@Model.Counter" />
                            <label class="col-form-label col-md-8 col-sm-8 ">
                                @Model.Agency_Name (@Model.User_Id)
                            </label>
                        </div>
                        <div class="col-sm-4 col-md-4">
                            <label class="col-form-label col-md-4 col-sm-4 ">
                                Available Balance
                            </label>
                            <label class="col-form-label col-md-8 col-sm-8 ">
                               Rs XXXX
                            </label>
                        </div>
                        <div class="col-sm-4 col-md-4">
                            <label class="col-form-label col-md-4 col-sm-4 ">
                                Due Amount
                            </label>
                            <label class="col-form-label col-md-8 col-sm-8 ">
                                @Model.DueAmount
                            </label>
                        </div>
                    </div>

                    <div class="item form-group">
                        <div class="col-sm-4 col-md-4">
                            <label class="col-form-label col-md-4 col-sm-4 ">
                               Set Credit Limit
                            </label>
                            <input type="text" name="creditlimit" value="@Model.Crd_Limit" required class="form-control" />
                        </div>
                        <div class="col-sm-4 col-md-4">
                            <label class="col-form-label col-md-4 col-sm-4 ">
                                Expiry Date
                            </label>
                            <input type="date" name="expirydate" value="" required class="form-control" />
                        </div>
                        <div class="col-sm-4 col-md-4">
                            <label class="col-form-label col-md-4 col-sm-4 ">
                                Remarks
                            </label>
                            <input type="text" name="remarks" value="@Model.Remark" class="form-control" />
                        </div>
                    </div>

                    <div class="item form-group">
                        <div class="col-md-3 col-sm-3 offset-md-9 ">
                            <button type="submit" class="btn btn-success pull-right">Submit</button>
                        </div>
                    </div>
                }
            </div>
        </div>
    </div>
</div>

@section footer
{
    <script src="~/Content/js/custom/common.js"></script>
    <script src="~/Content/design/dropdown_search_box/js/select2.min.js"></script>
    <script>
        $("#ddlAgencyList").select2();

    </script>
}