AdminPanel/AdminPanel/Controllers/FlightController.cs
using AdminPanel.Models;
using AdminPanel.Service;
using System.Web.Mvc;

namespace AdminPanel.Controllers
{
    public class FlightController : Controller
    {
        public ActionResult TicketReport(FlightModel model)
        {
            ExecuRegister lu = new ExecuRegister();
            if (AdministrationService.IsExecutiveLogin(ref lu))
            {
                model = FlightService.GetTicketReport(lu.role_type, lu.user_id, model);
            }
            return View(model);
        }
    }
}

AdminPanel/AdminPanel/Views/Flight/TicketReport.cshtml
@model AdminPanel.Models.FlightModel
@{
    ViewBag.Title = "LedgerList";
    Layout = "~/Views/Shared/_MasterLayoutPage.cshtml";
}
@section header{
    <link href="~/Content/design/css/custom/autocomplete.css" rel="stylesheet" />
    <link href="~/Content/design/dropdown_search_box/css/select2.min.css" rel="stylesheet" />
    <style>
        .wrapper {
            position: relative;
            overflow: auto;
            border: 1px solid black;
            white-space: nowrap;
        }

        .sticky-col {
            position: sticky;
            position: -webkit-sticky;
            background-color: #2A3F54;
            color: #fff;
            border-right: 1px solid #ccc;
        }

        .first-col {
            width: 140px;
            min-width: 140px;
            max-width: 140px;
            left: 0px;
        }
    </style>
}
<div class="row">
    <div class="x_panel">
        <div class="x_title">
            <h2>Ticket Report</h2>
            <ul class="nav navbar-right panel_toolbox">
                <li>
                    <button type="button" id="ResetFilter" class="btn btn-danger btn-sm">Reset Filter</button>
                </li>
            </ul>
            <div class="clearfix"></div>
        </div>
        <div class="x_content">

            @using (Html.BeginForm("TicketReport", "Flight", FormMethod.Post))
            {
                <div class="row">
                    <div class="col-md-2 col-sm-12  form-group">
                        @Html.TextBoxFor(p => p.FilterFromDate, new { @class = "form-control commoncss", placeholder = "From Date", @type = "date" })
                    </div>
                    <div class="col-md-2 col-sm-12  form-group">
                        @Html.TextBoxFor(p => p.FilterToDate, new { @class = "form-control commoncss", placeholder = "To Date", @type = "date" })
                    </div>
                    <div class="col-md-2 col-sm-12  form-group">
                        @Html.TextBoxFor(p => p.FilterPnr, new { @class = "form-control commoncss", placeholder = "Pnr", @type = "text" })
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        @Html.TextBoxFor(p => p.FilterOrderId, new { @class = "form-control commoncss", placeholder = "Order Id", @type = "text" })
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        @Html.TextBoxFor(p => p.FilterPaxName, new { @class = "form-control commoncss", placeholder = "Passenger Name", @type = "text" })
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-4 col-sm-12  form-group">
                        @Html.TextBoxFor(p => p.FilterAgencyName, new { @class = "form-control commoncss agencysearch", placeholder = "Agency Namd or Agency Id" })
                        <i class="fa fa-spinner faspinpositon fa-pulse agencyspin" style="position: absolute;right: 10px;font-size: 20px;top: 10px;color: red;display:none;"></i>
                        @Html.HiddenFor(p => p.FilterAgencyId, new { @class = "hdnagencyid" })
                    </div>
                    <div class="col-md-3 col-sm-12  form-group">
                        @*@Html.DropDownListFor(m => m.FilterTripType, Model.TripTypeList, "Select Trip Type", new { @class = "form-control commoncss" }), @onchange = "FillState()"*@
                        @Html.DropDownListFor(x => x.FilterTripType, new List<SelectListItem>
                            {
                                new SelectListItem() {Text = "Select Trip Type", Value=""},
                                new SelectListItem() {Text = "Domestic", Value="D"},
                                new SelectListItem() {Text = "International", Value="I"}
                            }, new { @class = "form-control commoncss" });
                    </div>

                    <div class="col-md-5 col-sm-12  form-group">
                        <button type="submit" class="btn btn-success btn-xs" id="btnSearch" onclick="return SearchLedDetl();">Search</button>
                        <button type="button" class="btn btn-info">Export</button>
                    </div>
                </div>
            }
        </div>
    </div>
    <div class="x_panel" style="padding: 0px!important;">
        <div class="x_content">
            <div class="row">
                <div class="col-sm-12" style="padding: 5px;">
                    <div class="col-md-3"><i class="fa fa-calculator" aria-hidden="true"></i> Total Ticket Count : @Model.TotalCount</div>
                    <div class="col-md-3">Total Ticket Sale Amount : <i class="fa fa-inr" aria-hidden="true"></i> @Model.TotalTicketAmount</div>
                    <div class="col-md-3"><i class="fa fa-calculator" aria-hidden="true"></i> Total Ticket Issued : @Model.TotalTicketIssued</div>
                </div>
                <div class="col-sm-12">
                    <div class="table-responsive text-nowrap tablescroll">
                        <table class="table" data-toggle="table" id="IncentiveTable">
                            <thead>
                                <tr style="background:#f6f6f6;">
                                    <th class="sticky-col first-col">Order ID</th>
                                    <th>Booking Date/Time</th>
                                    <th>AgencyID</th>
                                    <th>Agency Name</th>
                                    <th>GdsPnr</th>
                                    <th>AirlinePnr</th>
                                    <th>Sector</th>
                                    <th>Passenger</th>
                                    <th>Carrier</th>
                                    <th>Trip</th>
                                    <th>Trip Type</th>
                                    <th>Booking Gross Amount</th>
                                    <th>Booking Net Amount</th>
                                    <th>Ticket Status</th>
                                    <th>Supplier</th>
                                    <th>Executive</th>
                                </tr>
                            </thead>
                            <tbody id="tbodycomm">
                                @if (Model.TicketReportList != null && Model.TicketReportList.Count > 0)
                                {
                                    foreach (var item in Model.TicketReportList)
                                    {
                                        <tr>
                                            <td class="sticky-col first-col" style="background-color: #fff;"><a href="#" target="_blank" style="color: #fff; background-color: #17a2b8; border-color: #17a2b8; padding: 6px; border-radius: 2px;">@item.OrderId</a></td>
                                            <td>@item.CreateDate</td>
                                            <td>@item.AgentId</td>
                                            <td>@item.AgencyName</td>
                                            <td>@item.GdsPnr</td>
                                            <td>@item.AirlinePnr</td>
                                            <td>@item.sector</td>
                                            <td>@(item.PgTitle+" "+ item.PgFName+" "+ item.PgLName)</td>
                                            <td>@item.VC</td>
                                            <td>@item.Trip</td>
                                            <td>@item.TripType</td>
                                            <td>@item.TotalBookingCost</td>
                                            <td>@item.TotalAfterDis</td>
                                            @if (item.Status.ToLower().Trim() == "ticketed")
                                            {
                                                <td><span style="font-weight: bold; background: #28a745; color: #fff; padding: 5px; border-radius: 2px;"><i class="fa fa-check-circle" aria-hidden="true"></i> @item.Status</span></td>
                                            }
                                            else
                                            {
                                                <td>@item.Status</td>
                                            }
                                            <td>@item.SearchId</td>
                                            <td>@item.ExecutiveId</td>
                                        </tr>
                                    }
                                }
                                else
                                {
                                    <tr>
                                        <td colspan="17" class="text-center text-danger">No result found !</td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section footer
{
    <script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
    <script src="~/Content/js/custom/AgencySearch.js"></script>
    <script src="~/Content/design/dropdown_search_box/js/select2.min.js"></script>
    <script>
        //dropdown with search box
        $("#FilterTripType").select2();

        $("#ResetFilter").click(function () {
            $("#FilterFromDate").val(null);
            $("#FilterToDate").val(null);
            $("#FilterPnr").val(null);
            $("#FilterOrderId").val(null);
            $("#FilterPaxName").val(null);
            $("#FilterAgencyName").val(null);
            $("#FilterAgencyId").val(null);
            $("#FilterTripType").val(null);
        });

        SearchLedDetl = () => {
            $("#btnSearch").html("<i class='fa fa-pulse fa-spinner'></i>");
        }
    </script>
}